name: Trigger Aliyun Flow

# 仅在推送到main分支时触发
on:
  push:
    branches: [ main ]

jobs:
  trigger:
    runs-on: ubuntu-latest
    
    steps:
      - name: 触发阿里云Flow
        run: |
          curl --header "Content-Type: application/json" \
               --request POST \
               --data "{}" \
               http://flow-openapi.aliyun.com/scm/webhook/d2H5Otg8Hme1NaCif82s
